Repository KaanKalmi/dont-repeat-yourself-component-library, pull requests merged in 2024-11, with the labels that each got.

#21 Navbar styling update #1
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Program.svelte
Labels: documentation, Component

#23 Footer + Header component veranderingen
  src/lib/organisms/Footer.svelte
  src/lib/organisms/Nav.svelte
  static/css/globals.css
Labels: documentation, Component

#25 Mergin Main into my own branch
  package-lock.json
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/organisms/Semesters.svelte
Labels: documentation

#28 Added Agenda Toggle and Updated Schedule
  docs/fdnd.md
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Footer.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  static/css/globals.css
  static/img/FDND-Stickers-transparent.png
Labels: documentation, Component

#42 Migration to sveltekit 5!
  package-lock.json
  package.json
  src/lib/atoms/Calendar.svelte
  src/lib/atoms/HvaLogo.svelte
  src/lib/atoms/Star.svelte
  src/lib/atoms/Topic.svelte
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/molecules/StudentWork.svelte
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSemester.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Heading.svelte
  src/lib/organisms/Loader.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Program.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/lib/organisms/Tasks.svelte
  src/routes/+layout.svelte
  src/routes/+page.server.js
  src/routes/+page.svelte
  src/routes/[semester]/+page.svelte
  src/routes/[semester]/[sprint]/+page.svelte
Labels: enhancement

#46 Kaan branch updaten
  README.md
  package-lock.json
  package.json
  src/lib/atoms/Calendar.svelte
  src/lib/atoms/Star.svelte
  src/lib/atoms/Topic.svelte
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/molecules/StudentWork.svelte
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSemester.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Heading.svelte
  src/lib/organisms/Loader.svelte
  src/lib/organisms/Program.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/lib/organisms/Tasks.svelte
  src/routes/+layout.svelte
  src/routes/+page.server.js
  src/routes/+page.svelte
  src/routes/[semester]/+page.svelte
  src/routes/[semester]/[sprint]/+page.svelte
Labels: documentation

#53 Aanpassingen op de main padding + layout shift in media queries
  src/lib/molecules/Semester.svelte
  src/lib/organisms/Heading.svelte
  src/lib/organisms/Program.svelte
  src/lib/organisms/Semesters.svelte
  src/routes/+layout.svelte
Labels: documentation, Component

#55 Code conventions toegepast op de hele repository (CODE REFACTOR)
  src/lib/atoms/Calendar.svelte
  src/lib/atoms/Expand.svelte
  src/lib/atoms/HvaPayoff.svelte
  src/lib/atoms/Loader.svelte
  src/lib/atoms/Star.svelte
  src/lib/atoms/Task.svelte
  src/lib/atoms/Topic.svelte
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/molecules/StudentWork.svelte
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSemester.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Footer.svelte
  src/lib/organisms/Heading.svelte
  src/lib/organisms/Loader.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Program.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/lib/organisms/Tasks.svelte
  src/routes/+error.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/[semester]/+page.svelte
  src/routes/[semester]/[sprint]/+page.svelte
  static/css/globals.css
Labels: documentation

#57 ContentSprint, Tasks en Topics componenten
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Heading.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Tasks.svelte
  src/routes/+layout.svelte
  src/routes/[semester]/[sprint]/+page.svelte
Labels: documentation, Component

#64 small detail + lighthouse fixes
  src/app.html
  src/lib/atoms/HvaPayoff.svelte
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/molecules/StudentWork.svelte
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Heading.svelte
  src/lib/organisms/Loader.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Program.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/lib/organisms/Tasks.svelte
  src/lib/stores/program.js
  src/lib/utils/client.js
  src/lib/utils/date.js
  src/routes/+page.server.js
  src/routes/[semester]/+page.server.js
  src/routes/[semester]/[sprint]/+page.server.js
  static/robots.txt
  svelte.config.js
Labels: documentation, enhancement, Component

#65 Semester pagina layout versie 1
  src/lib/organisms/ContentSemester.svelte
  src/lib/organisms/Program.svelte
  src/routes/[semester]/+page.svelte
Labels: documentation, Component

#67 Pull request to get the next page
  src/app.html
  src/lib/atoms/HvaPayoff.svelte
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/molecules/StudentWork.svelte
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSemester.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Heading.svelte
  src/lib/organisms/Loader.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Program.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/lib/organisms/Tasks.svelte
  src/lib/stores/program.js
  src/lib/utils/client.js
  src/lib/utils/date.js
  src/routes/+layout.svelte
  src/routes/+page.server.js
  src/routes/+page.svelte
  src/routes/[semester]/+page.server.js
  src/routes/[semester]/+page.svelte
  src/routes/[semester]/[sprint]/+page.server.js
  static/robots.txt
  svelte.config.js
Labels: documentation, Component
